#
# Standard configuration
#
baseURL                = "https://johnwry.github.io/page/"
copyright              = "The MIT License (MIT) Copyright © 2020 BJWry"
rssLimit = 10
defaultContentLanguage = "en"
enableEmoji            = false
# enableGitInfo          = true
metaDataFormat         = "yaml"
publishDir             = "docs"
title                  = "BJWry"
theme                  = "shadocs"
# themesdir              = "../page/themes"
custom_css = ["css/custom.css"]

# pygmentsUseClasses=false
# pygmentsCodeFences=false

[Author]
  name = "BJWry"
  email = "johnwry@gmail.com"


[module]
  [module.hugoVersion]
    extended = true
    min = '0.112.0'
    max = ''
  [[module.mounts]]
    source = 'asyncapi'
    target = 'static/asyncapi'
  [[module.mounts]]
    source = 'openapi'
    target = 'static/openapi'

#[taxonomies]
#  category = "categories"
#  tag = "tags"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = false



#
# Specific configuration
#
[params]
  logo                    = "images/logo.png"
  logoTouch               = "images/logoTouch.png"
  image404                = "images/404.gif"
  favicon                 = "images/favicon.png"
  faviconmd               = "![Favicon](/images/favicon.png)"
  homeLayout              = "onboarding"
  siteContentOrder        = "weight"
  toc                     = true
  # globalBanner          = true
  currentVersion          = "latest"
  latestVersionUrl        = "https://shadocs.netlify.app/"


  # enforceRefrelLinks    = true
  [params.navbar.shortcuts]
    [params.navbar.shortcuts.example]
      keys     = ["Shift","1"]
      function = "scExample"
  [[params.navbar.versions]]
    name = 'latest'
    url  = 'https://shadocs.netlify.app/'
  [[params.navbar.versions]]
    name = 'deprecated version'
    url  = 'https://shadocs.netlify.app/404.html'
  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
      icon = "fa-solid fa-tag"
  #[params.includes]
  #  jsModules = [
  #      "js/shortcuts.js"
  #    ]
  #  js        = []
  #  css       = [
  #      "css/shortcuts.css"
  #    ]
  #  sass      = [
  #      "sass/custom/example.sass"
  #  ]

  [params.versions]
    hugo_min         = "[0.112.0](https://github.com/gohugoio/hugo/releases/tag/v0.112.0)"
    bulma            = "[0.9.4](https://github.com/jgthms/bulma/releases/tag/0.9.4)"
